---
name: Document-Maker
version: 0.01_02
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
abstract: Document::Maker
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Path::Class: 0
  Scalar::Util: 0
build_requires:
  Directory::Scratch: 0
  Test::More: 0
provides:
  Document::Magick::Maker::Rule:
    file: lib/Document/Maker.pm
  Document::Magick::Maker::Rule::Map:
    file: lib/Document/Maker.pm
  Document::Maker:
    file: lib/Document/Maker.pm
    version: 0.01_02
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
